2025-05-17 23:13:56 - INFO - Data being sent successfully.
2025-05-17 23:13:57 - INFO - Data being sent successfully.
2025-05-17 23:14:02 - INFO - Data being sent successfully.
2025-05-17 23:14:03 - INFO - Data being sent successfully.
2025-05-17 23:14:08 - INFO - Data being sent successfully.
2025-05-17 23:14:08 - INFO - Data being sent successfully.
2025-05-17 23:14:14 - INFO - Data being sent successfully.
2025-05-17 23:14:14 - INFO - Data being sent successfully.
2025-05-17 23:14:19 - INFO - Data being sent successfully.
2025-05-17 23:14:20 - INFO - Data being sent successfully.
2025-05-17 23:14:25 - INFO - Data being sent successfully.
2025-05-17 23:14:26 - INFO - Data being sent successfully.
2025-05-17 23:14:31 - INFO - Data being sent successfully.
2025-05-17 23:14:31 - INFO - Data being sent successfully.
2025-05-17 23:14:37 - INFO - Data being sent successfully.
2025-05-17 23:14:37 - INFO - Data being sent successfully.
2025-05-17 23:14:42 - INFO - Data being sent successfully.
2025-05-17 23:14:43 - INFO - Data being sent successfully.
2025-05-17 23:14:48 - INFO - Data being sent successfully.
2025-05-17 23:14:49 - INFO - Data being sent successfully.
2025-05-17 23:14:54 - INFO - Data being sent successfully.
2025-05-17 23:14:54 - INFO - Data being sent successfully.
2025-05-17 23:15:00 - INFO - Data being sent successfully.
2025-05-17 23:15:00 - INFO - Data being sent successfully.
2025-05-17 23:15:05 - INFO - Data being sent successfully.
2025-05-17 23:15:06 - INFO - Data being sent successfully.
2025-05-17 23:15:11 - INFO - Data being sent successfully.
2025-05-17 23:15:11 - INFO - Data being sent successfully.
2025-05-17 23:15:18 - INFO - Data being sent successfully.
2025-05-17 23:15:19 - INFO - Data being sent successfully.
2025-05-17 23:15:24 - INFO - Data being sent successfully.
2025-05-17 23:15:24 - INFO - Data being sent successfully.
2025-05-17 23:15:32 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3CC310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:15:34 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3CC8B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:15:41 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3EE2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:15:44 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3EEC70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:15:51 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3CC8B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:15:53 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3EED30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:16:01 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3EE1F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:16:03 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD404640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:16:10 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AB10AF40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:16:12 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000273AD3EE7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-17 23:16:18 - INFO - Data being sent successfully.
2025-05-17 23:16:18 - INFO - Data being sent successfully.
2025-05-17 23:16:24 - INFO - Data being sent successfully.
2025-05-17 23:16:24 - INFO - Data being sent successfully.
2025-05-18 15:50:19 - INFO - Data being sent successfully.
2025-05-18 15:50:20 - INFO - Data being sent successfully.
2025-05-18 15:50:25 - INFO - Data being sent successfully.
2025-05-18 15:50:31 - INFO - Data being sent successfully.
2025-05-18 15:50:42 - INFO - Data being sent successfully.
2025-05-18 15:50:48 - INFO - Data being sent successfully.
2025-05-18 15:50:53 - INFO - Data being sent successfully.
2025-05-18 15:50:53 - INFO - Data being sent successfully.
2025-05-18 15:50:59 - INFO - Data being sent successfully.
2025-05-18 15:51:04 - INFO - Data being sent successfully.
2025-05-18 15:52:18 - INFO - Data being sent successfully.
2025-05-18 15:52:18 - INFO - Data being sent successfully.
2025-05-18 15:52:23 - INFO - Data being sent successfully.
2025-05-18 15:52:24 - INFO - Data being sent successfully.
2025-05-18 15:52:29 - INFO - Data being sent successfully.
2025-05-18 15:52:29 - INFO - Data being sent successfully.
2025-05-18 15:52:36 - INFO - Data being sent successfully.
2025-05-18 15:52:37 - INFO - Data being sent successfully.
2025-05-18 16:35:46 - INFO - Data being sent successfully.
2025-05-18 16:35:46 - INFO - Data being sent successfully.
2025-05-18 16:35:52 - INFO - Data being sent successfully.
2025-05-18 16:35:52 - INFO - Data being sent successfully.
2025-05-18 16:35:57 - INFO - Data being sent successfully.
2025-05-18 16:35:58 - INFO - Data being sent successfully.
2025-05-18 16:36:03 - INFO - Data being sent successfully.
2025-05-18 16:36:03 - INFO - Data being sent successfully.
2025-05-18 16:36:09 - INFO - Data being sent successfully.
2025-05-18 16:36:09 - INFO - Data being sent successfully.
2025-05-18 16:36:15 - INFO - Data being sent successfully.
2025-05-18 16:36:15 - INFO - Data being sent successfully.
2025-05-18 16:36:21 - INFO - Data being sent successfully.
2025-05-18 16:36:21 - INFO - Data being sent successfully.
2025-05-18 16:36:26 - INFO - Data being sent successfully.
2025-05-18 16:36:27 - INFO - Data being sent successfully.
2025-05-18 16:36:32 - INFO - Data being sent successfully.
2025-05-18 16:36:32 - INFO - Data being sent successfully.
2025-05-18 16:36:38 - INFO - Data being sent successfully.
2025-05-18 16:36:38 - INFO - Data being sent successfully.
2025-05-18 16:36:44 - INFO - Data being sent successfully.
2025-05-18 16:36:44 - INFO - Data being sent successfully.
2025-05-18 16:36:49 - INFO - Data being sent successfully.
2025-05-18 16:36:50 - INFO - Data being sent successfully.
2025-05-18 16:36:55 - INFO - Data being sent successfully.
2025-05-18 16:36:56 - INFO - Data being sent successfully.
2025-05-18 16:37:01 - INFO - Data being sent successfully.
2025-05-18 16:37:01 - INFO - Data being sent successfully.
2025-05-18 16:37:07 - INFO - Data being sent successfully.
2025-05-18 16:37:07 - INFO - Data being sent successfully.
2025-05-18 16:37:13 - INFO - Data being sent successfully.
2025-05-18 16:37:13 - INFO - Data being sent successfully.
2025-05-18 16:37:20 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000012E66A9C5E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:38:00 - INFO - Data being sent successfully.
2025-05-18 16:38:00 - INFO - Data being sent successfully.
2025-05-18 16:38:05 - INFO - Data being sent successfully.
2025-05-18 16:38:06 - INFO - Data being sent successfully.
2025-05-18 16:38:11 - INFO - Data being sent successfully.
2025-05-18 16:38:12 - INFO - Data being sent successfully.
2025-05-18 16:38:57 - INFO - Data being sent successfully.
2025-05-18 16:39:02 - INFO - Data being sent successfully.
2025-05-18 16:39:03 - INFO - Data being sent successfully.
2025-05-18 16:39:08 - INFO - Data being sent successfully.
2025-05-18 16:39:08 - INFO - Data being sent successfully.
2025-05-18 16:39:14 - INFO - Data being sent successfully.
2025-05-18 16:39:14 - INFO - Data being sent successfully.
2025-05-18 16:39:20 - INFO - Data being sent successfully.
2025-05-18 16:39:20 - INFO - Data being sent successfully.
2025-05-18 16:39:25 - INFO - Data being sent successfully.
2025-05-18 16:39:26 - INFO - Data being sent successfully.
2025-05-18 16:39:31 - INFO - Data being sent successfully.
2025-05-18 16:39:32 - INFO - Data being sent successfully.
2025-05-18 16:39:39 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B709BDB80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:39:41 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B709FC520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:39:49 - INFO - Data being sent successfully.
2025-05-18 16:39:49 - INFO - Data being sent successfully.
2025-05-18 16:39:57 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B709BDAC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:41:16 - INFO - Data being sent successfully.
2025-05-18 16:41:16 - INFO - Data being sent successfully.
2025-05-18 16:41:22 - INFO - Data being sent successfully.
2025-05-18 16:41:22 - INFO - Data being sent successfully.
2025-05-18 16:41:29 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA84BDC970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:41:32 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA84BDC670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:41:39 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA84C182E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:41:41 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA84C18D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:41:49 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA822ABBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:41:51 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA84BDC670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:41:58 - INFO - Data being sent successfully.
2025-05-18 16:41:58 - INFO - Data being sent successfully.
2025-05-18 16:42:03 - INFO - Data being sent successfully.
2025-05-18 16:42:04 - INFO - Data being sent successfully.
2025-05-18 16:42:09 - INFO - Data being sent successfully.
2025-05-18 16:42:09 - INFO - Data being sent successfully.
2025-05-18 16:42:17 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA83BAC370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:42:19 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA84C329A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:42:25 - INFO - Data being sent successfully.
2025-05-18 16:42:26 - INFO - Data being sent successfully.
2025-05-18 16:42:31 - INFO - Data being sent successfully.
2025-05-18 16:42:32 - INFO - Data being sent successfully.
2025-05-18 16:45:28 - INFO - Data being sent successfully.
2025-05-18 16:45:28 - INFO - Data being sent successfully.
2025-05-18 16:45:34 - INFO - Data being sent successfully.
2025-05-18 16:45:34 - INFO - Data being sent successfully.
2025-05-18 16:45:40 - INFO - Data being sent successfully.
2025-05-18 16:45:40 - INFO - Data being sent successfully.
2025-05-18 16:45:45 - INFO - Data being sent successfully.
2025-05-18 16:45:46 - INFO - Data being sent successfully.
2025-05-18 16:45:51 - INFO - Data being sent successfully.
2025-05-18 16:45:52 - INFO - Data being sent successfully.
2025-05-18 16:45:57 - INFO - Data being sent successfully.
2025-05-18 16:45:57 - INFO - Data being sent successfully.
2025-05-18 16:46:05 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001710998C6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:46:53 - INFO - Data being sent successfully.
2025-05-18 16:46:59 - INFO - Data being sent successfully.
2025-05-18 16:46:59 - INFO - Data being sent successfully.
2025-05-18 16:48:21 - INFO - Data being sent successfully.
2025-05-18 16:48:21 - INFO - Data being sent successfully.
2025-05-18 16:48:27 - INFO - Data being sent successfully.
2025-05-18 16:48:27 - INFO - Data being sent successfully.
2025-05-18 16:48:34 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A221F4DB50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:48:44 - INFO - Data being sent successfully.
2025-05-18 16:48:45 - ERROR - An error occurred while requesting inserting datas. ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
2025-05-18 16:48:52 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD23ACAF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:48:54 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD23EC2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:49:02 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD23ECCD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:49:04 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD23ECCD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:49:11 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD23AC670>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:49:12 - INFO - Data being sent successfully.
2025-05-18 16:49:18 - INFO - Data being sent successfully.
2025-05-18 16:49:18 - INFO - Data being sent successfully.
2025-05-18 16:49:23 - INFO - Data being sent successfully.
2025-05-18 16:49:24 - INFO - Data being sent successfully.
2025-05-18 16:49:29 - INFO - Data being sent successfully.
2025-05-18 16:49:29 - INFO - Data being sent successfully.
2025-05-18 16:49:37 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /insert-product/dtdd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DD137B190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"))
2025-05-18 16:51:35 - INFO - Data being sent successfully.
2025-05-18 16:51:36 - INFO - Data being sent successfully.
2025-05-18 16:51:41 - INFO - Data being sent successfully.
2025-05-18 16:51:41 - INFO - Data being sent successfully.
2025-05-18 16:51:47 - INFO - Data being sent successfully.
2025-05-18 16:51:47 - INFO - Data being sent successfully.
2025-05-18 10:30:38 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0c581c16a0>: Failed to resolve \'database_api\' ([Errno -2] Name or service not known)"))'))
2025-05-18 10:30:41 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0c58201bd0>: Failed to resolve \'database_api\' ([Errno -2] Name or service not known)"))'))
2025-05-18 10:30:50 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0c58202350>: Failed to resolve \'database_api\' ([Errno -2] Name or service not known)"))'))
2025-05-18 10:30:53 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0c58224180>: Failed to resolve \'database_api\' ([Errno -2] Name or service not known)"))'))
2025-05-18 10:32:16 - INFO - Data being sent successfully.
2025-05-18 10:32:16 - INFO - Data being sent successfully.
2025-05-18 10:32:21 - INFO - Data being sent successfully.
2025-05-18 10:32:22 - INFO - Data being sent successfully.
2025-05-18 10:32:27 - INFO - Data being sent successfully.
2025-05-18 10:32:27 - INFO - Data being sent successfully.
2025-05-18 10:32:32 - INFO - Data being sent successfully.
2025-05-18 10:32:33 - INFO - Data being sent successfully.
2025-05-18 10:32:33 - INFO - Data being sent successfully.
2025-05-18 10:32:38 - INFO - Data being sent successfully.
2025-05-18 10:32:39 - INFO - Data being sent successfully.
2025-05-18 10:32:44 - INFO - Data being sent successfully.
2025-05-18 10:32:44 - INFO - Data being sent successfully.
2025-05-18 10:32:50 - INFO - Data being sent successfully.
2025-05-18 10:32:50 - INFO - Data being sent successfully.
2025-05-18 10:32:55 - INFO - Data being sent successfully.
2025-05-18 10:32:56 - INFO - Data being sent successfully.
2025-05-18 10:33:01 - INFO - Data being sent successfully.
2025-05-18 10:33:01 - INFO - Data being sent successfully.
2025-05-18 10:33:06 - INFO - Data being sent successfully.
2025-05-18 10:33:07 - INFO - Data being sent successfully.
2025-05-18 10:33:12 - INFO - Data being sent successfully.
2025-05-18 10:33:12 - INFO - Data being sent successfully.
2025-05-18 10:33:18 - INFO - Data being sent successfully.
2025-05-18 10:33:18 - INFO - Data being sent successfully.
2025-05-18 10:33:23 - INFO - Data being sent successfully.
2025-05-18 10:33:24 - INFO - Data being sent successfully.
2025-05-18 10:33:29 - INFO - Data being sent successfully.
2025-05-18 10:33:29 - INFO - Data being sent successfully.
2025-05-18 10:33:35 - INFO - Data being sent successfully.
2025-05-18 10:33:35 - INFO - Data being sent successfully.
2025-05-18 10:33:40 - INFO - Data being sent successfully.
2025-05-18 10:33:41 - INFO - Data being sent successfully.
2025-05-18 10:33:46 - INFO - Data being sent successfully.
2025-05-18 10:33:46 - INFO - Data being sent successfully.
2025-05-18 10:33:52 - INFO - Data being sent successfully.
2025-05-18 10:33:52 - INFO - Data being sent successfully.
2025-05-18 10:33:57 - INFO - Data being sent successfully.
2025-05-18 10:33:58 - INFO - Data being sent successfully.
2025-05-18 10:38:57 - INFO - Data being sent successfully.
2025-05-18 10:38:57 - INFO - Data being sent successfully.
2025-05-18 10:39:03 - INFO - Data being sent successfully.
2025-05-18 10:39:03 - INFO - Data being sent successfully.
2025-05-18 10:39:08 - INFO - Data being sent successfully.
2025-05-18 10:39:09 - INFO - Data being sent successfully.
2025-05-18 10:39:14 - INFO - Data being sent successfully.
2025-05-18 10:39:14 - INFO - Data being sent successfully.
2025-05-18 10:39:20 - INFO - Data being sent successfully.
2025-05-18 10:39:20 - INFO - Data being sent successfully.
2025-05-18 10:39:25 - INFO - Data being sent successfully.
2025-05-18 10:39:26 - INFO - Data being sent successfully.
2025-05-18 10:39:31 - INFO - Data being sent successfully.
2025-05-18 10:39:31 - INFO - Data being sent successfully.
2025-05-18 10:39:37 - INFO - Data being sent successfully.
2025-05-18 10:39:37 - INFO - Data being sent successfully.
2025-05-18 10:39:42 - INFO - Data being sent successfully.
2025-05-18 10:39:43 - INFO - Data being sent successfully.
2025-05-18 10:39:48 - INFO - Data being sent successfully.
2025-05-18 10:39:49 - INFO - Data being sent successfully.
2025-05-18 10:39:54 - INFO - Data being sent successfully.
2025-05-18 10:39:54 - INFO - Data being sent successfully.
2025-05-18 10:40:00 - INFO - Data being sent successfully.
2025-05-18 10:40:00 - INFO - Data being sent successfully.
2025-05-18 10:40:05 - INFO - Data being sent successfully.
2025-05-18 10:40:06 - INFO - Data being sent successfully.
2025-05-18 10:40:11 - INFO - Data being sent successfully.
2025-05-18 10:40:12 - INFO - Data being sent successfully.
2025-05-18 10:40:17 - INFO - Data being sent successfully.
2025-05-18 10:40:17 - INFO - Data being sent successfully.
2025-05-18 10:40:23 - INFO - Data being sent successfully.
2025-05-18 10:40:23 - INFO - Data being sent successfully.
2025-05-18 10:40:28 - INFO - Data being sent successfully.
2025-05-18 10:40:29 - INFO - Data being sent successfully.
2025-05-18 10:40:34 - INFO - Data being sent successfully.
2025-05-18 10:40:34 - INFO - Data being sent successfully.
2025-05-18 10:40:40 - INFO - Data being sent successfully.
2025-05-18 10:40:40 - INFO - Data being sent successfully.
2025-05-18 10:40:45 - INFO - Data being sent successfully.
2025-05-18 10:40:46 - INFO - Data being sent successfully.
2025-05-18 10:43:33 - INFO - Data being sent successfully.
2025-05-18 10:43:33 - INFO - Data being sent successfully.
2025-05-18 10:43:39 - INFO - Data being sent successfully.
2025-05-18 10:43:39 - INFO - Data being sent successfully.
2025-05-18 10:43:44 - INFO - Data being sent successfully.
2025-05-18 10:43:45 - INFO - Data being sent successfully.
2025-05-18 10:43:50 - INFO - Data being sent successfully.
2025-05-18 10:43:50 - INFO - Data being sent successfully.
2025-05-18 10:43:56 - INFO - Data being sent successfully.
2025-05-18 10:43:56 - INFO - Data being sent successfully.
2025-05-18 10:44:01 - INFO - Data being sent successfully.
2025-05-18 10:44:02 - INFO - Data being sent successfully.
2025-05-18 10:44:07 - INFO - Data being sent successfully.
2025-05-18 10:44:07 - INFO - Data being sent successfully.
2025-05-18 10:49:57 - INFO - Data being sent successfully.
2025-05-18 10:49:57 - INFO - Data being sent successfully.
2025-05-18 10:50:02 - INFO - Data being sent successfully.
2025-05-18 10:50:03 - INFO - Data being sent successfully.
2025-05-18 10:50:08 - INFO - Data being sent successfully.
2025-05-18 10:50:08 - INFO - Data being sent successfully.
2025-05-18 10:50:14 - INFO - Data being sent successfully.
2025-05-18 10:50:14 - INFO - Data being sent successfully.
2025-05-18 10:50:19 - INFO - Data being sent successfully.
2025-05-18 10:50:20 - INFO - Data being sent successfully.
2025-05-18 10:50:25 - INFO - Data being sent successfully.
2025-05-18 10:50:25 - INFO - Data being sent successfully.
2025-05-18 10:54:13 - INFO - Data being sent successfully.
2025-05-18 10:54:13 - INFO - Data being sent successfully.
2025-05-18 10:54:19 - INFO - Data being sent successfully.
2025-05-18 10:54:19 - INFO - Data being sent successfully.
2025-05-18 10:54:24 - INFO - Data being sent successfully.
2025-05-18 10:54:25 - INFO - Data being sent successfully.
2025-05-18 21:33:22 - ERROR - An error occurred while requesting inserting  phone datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001D11135DA60>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None 
2025-05-18 21:35:34 - ERROR - An error occurred while requesting inserting  phone datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000024BCF17DA60>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None 
2025-05-18 21:35:36 - ERROR - An error occurred while requesting inserting laptop datas. 
 ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/laptop (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000024BCF19C7C0>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None
2025-05-18 21:36:09 - ERROR - An error occurred while requesting inserting  phone datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001E2AB7BDA60>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None 
2025-05-18 21:36:12 - ERROR - An error occurred while requesting inserting laptop datas. 
 ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/laptop (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001E2AB7DC7C0>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None
2025-05-18 21:36:19 - ERROR - An error occurred while requesting inserting  phone datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F2E077DA60>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None 
2025-05-18 21:36:41 - ERROR - An error occurred while requesting inserting  phone datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002BB5419DA60>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None 
2025-05-18 21:36:56 - ERROR - An error occurred while requesting inserting  phone datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001D62F67DA60>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 None 
2025-05-18 14:51:38 - ERROR - An error occurred while requesting inserting datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f50697b16a0>: Failed to resolve \'database_api\' ([Errno -2] Name or service not known)"))'))
2025-05-18 22:54:16 - ERROR - An error occurred while requesting inserting  phone datas. ConnectionError(MaxRetryError('HTTPConnectionPool(host=\'database_api\', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002481C46FA60>: Failed to resolve \'database_api\' ([Errno 11001] getaddrinfo failed)"))')) 
 Traceback (most recent call last):
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\Anaconda\envs\KDL\lib\socket.py", line 930, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connection.py", line 441, in request
    self.endheaders()
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 951, in send
    self.connect()
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connection.py", line 279, in connect
    self.sock = self._new_conn()
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connection.py", line 206, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x000002481C46FA60>: Failed to resolve 'database_api' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='database_api', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002481C46FA60>: Failed to resolve 'database_api' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\app\ingestion.py", line 50, in sending_phone_datas
    requests.post('http://database_api:8002/insert-product/dtdd', json=productDict[i])
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='database_api', port=8002): Max retries exceeded with url: /insert-product/dtdd (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002481C46FA60>: Failed to resolve 'database_api' ([Errno 11001] getaddrinfo failed)"))
 
2025-05-18 23:07:39 - ERROR - An error occurred while requesting inserting laptop datas. 
 ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))) 
 Traceback (most recent call last):
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Anaconda\envs\KDL\lib\socket.py", line 681, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "D:\Anaconda\envs\KDL\lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\Anaconda\envs\KDL\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Anaconda\envs\KDL\lib\socket.py", line 681, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_ingestion\.\app\ingestion.py", line 86, in sending_laptop_datas
    requests.post('http://localhost:8002/insert-product/laptop', json=productDict[i])
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

