2025-05-16 18:44:07 - ERROR - An error occurred: {str(e)}
2025-05-16 18:44:07 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-16 18:44:12 - ERROR - An error occurred: {str(e)}
2025-05-16 18:44:12 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-16 18:44:17 - ERROR - An error occurred: {str(e)}
2025-05-16 18:44:17 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-16 18:44:22 - ERROR - An error occurred: {str(e)}
2025-05-16 18:44:22 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-16 18:44:27 - ERROR - An error occurred: {str(e)}
2025-05-16 18:44:27 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:05:30 - ERROR - An error occurred: {str(e)}
2025-05-17 10:05:30 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:05:35 - ERROR - An error occurred: {str(e)}
2025-05-17 10:05:35 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:05:40 - ERROR - An error occurred: {str(e)}
2025-05-17 10:05:40 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:05:45 - ERROR - An error occurred: {str(e)}
2025-05-17 10:05:45 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:05:50 - ERROR - An error occurred: {str(e)}
2025-05-17 10:05:50 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:05:55 - ERROR - An error occurred: {str(e)}
2025-05-17 10:05:55 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:00 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:00 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:05 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:05 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:10 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:10 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:15 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:15 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:15 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:15 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:20 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:20 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:23 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:23 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:25 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:25 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:06:30 - ERROR - An error occurred: {str(e)}
2025-05-17 10:06:30 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:13:11 - ERROR - An error occurred: {str(e)}
2025-05-17 10:13:11 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:13:13 - ERROR - An error occurred: {str(e)}
2025-05-17 10:13:13 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:13:16 - ERROR - An error occurred: {str(e)}
2025-05-17 10:13:16 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:13:35 - ERROR - An error occurred: {str(e)}
2025-05-17 10:13:35 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:13:39 - ERROR - An error occurred: {str(e)}
2025-05-17 10:13:39 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:13:41 - ERROR - An error occurred: {str(e)}
2025-05-17 10:13:41 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:15:43 - ERROR - An error occurred: {str(e)}
2025-05-17 10:15:43 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
2025-05-17 10:18:12 - ERROR - An error occurred: {str(e)}
2025-05-17 10:18:12 - ERROR - Traceback:
Traceback (most recent call last):
  File "D:\Projects\Python\224-CDCSDL-FinalProject\base\data_crawling\.\app\crawler.py", line 25, in phone_crawling
    htmlText = requests.get('', headers=headers).text
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "D:\Anaconda\envs\KDL\lib\site-packages\requests\models.py", line 438, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
